"use client";
import { useEffect, useState } from "react";

declare global { interface Window { vibaocodeDesktop?: { getInfo:()=>Promise<{version:string}>; update:()=>Promise<{ok:boolean;message?:string}>; onUpdateStatus:(cb:(p:{status:string;message?:string;percent?:number})=>void)=>()=>void } } }
type Stats={runtime:string;totalMemory?:number;usedMemory?:number;appRss?:number;cpuCount?:number;workspaceRoot?:string;projects?:Array<{repo:string;running:boolean;port:number}>};
const btn:React.CSSProperties={border:"1px solid #334155",background:"#111827",color:"#e5e7eb",borderRadius:9,padding:"9px 10px",fontSize:12,fontWeight:700,cursor:"pointer"};
const gb=(n=0)=>(n/1073741824).toFixed(1);
export default function LocalControlPanel(){
 const [s,setS]=useState<Stats|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(""),[msg,setMsg]=useState(""),[ver,setVer]=useState(""),[pct,setPct]=useState<number|null>(null);
 const refresh=async()=>{try{setS(await (await fetch("/api/local/system",{cache:"no-store"})).json())}catch{}};
 useEffect(()=>{refresh();const t=setInterval(refresh,5000);window.vibaocodeDesktop?.getInfo().then(x=>setVer(x.version));const off=window.vibaocodeDesktop?.onUpdateStatus(p=>{setMsg(p.message||p.status);if(typeof p.percent==="number")setPct(p.percent);if(["error","current"].includes(p.status))setBusy("")});return()=>{clearInterval(t);off?.()}},[]);
 if(s?.runtime!=="local")return null;const ram=s.totalMemory&&s.usedMemory?Math.round(s.usedMemory/s.totalMemory*100):0;
 const act=async(action:string)=>{setBusy(action);setMsg("");try{const r=await fetch("/api/local/system",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw new Error(d.error);setS(d.stats);setMsg(action==="optimize"?`Đã dừng ${d.stopped||0} process nhàn rỗi.`:action==="cleanCache"?`Đã dọn ${d.removed||0} mục cache cũ.`:`Đã dừng ${d.stopped||0} project.`)}catch(e){setMsg(e instanceof Error?e.message:"Thao tác thất bại") }finally{setBusy("")}};
 const update=async()=>{if(!window.vibaocodeDesktop){setMsg("Update tự động chỉ hoạt động trong bản Desktop.");return}setBusy("update");setPct(null);const r=await window.vibaocodeDesktop.update();setMsg(r.message||"");if(!r.ok)setBusy("")};
 return <div style={{position:"fixed",right:14,bottom:14,zIndex:99999,color:"#e5e7eb"}}>{open?<div style={{width:330,maxWidth:"calc(100vw - 28px)",background:"rgba(9,13,22,.97)",border:"1px solid #334155",borderRadius:16,padding:14,boxShadow:"0 20px 60px #0008"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><b>LOCAL SYSTEM</b><div style={{fontSize:11,opacity:.65}}>Vibaocode {ver&&`v${ver}`}</div></div><button style={btn} onClick={()=>setOpen(false)}>×</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginTop:10,fontSize:12}}><Box k="RAM" v={`${ram}% · ${gb(s.usedMemory)} / ${gb(s.totalMemory)} GB`}/><Box k="Vibaocode" v={`${Math.round((s.appRss||0)/1048576)} MB`}/><Box k="CPU" v={`${s.cpuCount||"-"} luồng`}/><Box k="Projects" v={String(s.projects?.filter(p=>p.running).length||0)}/></div><div style={{fontSize:10,opacity:.6,marginTop:9,wordBreak:"break-all"}}>Workspace: {s.workspaceRoot}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginTop:10}}><button style={btn} disabled={!!busy} onClick={()=>act("optimize")}>Tối ưu bộ nhớ</button><button style={btn} disabled={!!busy} onClick={()=>act("cleanCache")}>Dọn cache</button><button style={btn} disabled={!!busy} onClick={()=>act("stopAll")}>Dừng project</button><button style={{...btn,color:"#bbf7d0",borderColor:"#166534"}} disabled={!!busy} onClick={update}>{busy==="update"?(pct!=null?`Update ${Math.round(pct)}%`:"Đang update…"):"Update Vibaocode"}</button></div>{msg&&<div style={{fontSize:11,marginTop:9,lineHeight:1.4}}>{msg}</div>}</div>:<button style={{...btn,boxShadow:"0 10px 30px #0007"}} onClick={()=>setOpen(true)}>● LOCAL · RAM {ram}%</button>}</div>
}
function Box({k,v}:{k:string;v:string}){return <div style={{background:"#ffffff0b",borderRadius:9,padding:8}}><div style={{opacity:.6}}>{k}</div><b>{v}</b></div>}
